# Generated by Django 4.2.7 on 2023-12-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('prompt', models.CharField(blank=True, max_length=10000)),
                ('response', models.CharField(blank=True, max_length=5000)),
            ],
        ),
    ]
