# Generated by Django 4.2.7 on 2023-12-21 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instruction', '0002_conversation_problem_alter_conversation_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='prompt',
            new_name='essay',
        ),
    ]
